# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 12:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigateUrlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_url', models.URLField()),
                ('created_date', models.DateField(default=datetime.date.today, help_text=b'Created Date')),
                ('modified_date', models.DateField(default=datetime.date.today, help_text=b'Modified Date')),
            ],
            options={
                'verbose_name': 'Investigate URL',
                'verbose_name_plural': 'Investigate URLs',
            },
        ),
        migrations.CreateModel(
            name='PhishVerdictModel',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.FloatField(blank=True, null=True)),
                ('url_sha', models.TextField(blank=True, null=True, unique=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('internal_download_path', models.FileField(blank=True, null=True, upload_to=b'uploads/%Y/%m/%d')),
                ('comments', models.TextField(blank=True, help_text=b'Any Comments, Notes', null=True)),
                ('analysis_stage', models.IntegerField(choices=[(0, b'New|Waiting'), (1, b'Crawl'), (2, b'Extraction'), (3, b'Query Model'), (4, b'Complete')], default=0, help_text=b'Verdict Analysis Stage')),
                ('created_date', models.DateField(blank=True, default=datetime.date.today, help_text=b'Created Date', null=True)),
                ('modified_date', models.DateField(blank=True, default=datetime.date.today, help_text=b'Modified Date', null=True)),
                ('investigate_url', models.ForeignKey(help_text=b'Investigate Url', on_delete=django.db.models.deletion.CASCADE, related_name='modelqueue_phishverdictmodel_related', to='modelqueue.InvestigateUrlModel', verbose_name=b'Investigate Url FK')),
            ],
            options={
                'verbose_name': 'Verdict',
                'verbose_name_plural': 'Verdicts',
            },
        ),
        migrations.CreateModel(
            name='UserLicenseVerdictMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userlicenseusage', models.ForeignKey(help_text=b'User License Usage', on_delete=django.db.models.deletion.CASCADE, related_name='modelqueue_userlicenseverdictmap_related', to='licenseapp.UserLicenseUsage', verbose_name=b'User License Usage FK')),
                ('verdict', models.ForeignKey(help_text=b'Verdict FK', on_delete=django.db.models.deletion.CASCADE, related_name='modelqueue_userlicenseverdictmap_related', to='modelqueue.PhishVerdictModel', verbose_name=b'Verdict FK')),
            ],
        ),
    ]
