# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelqueue', '0002_auto_20160114_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffloadTasksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sha', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('created_date', models.DateField(blank=True, default=datetime.date.today, help_text=b'Created Date', null=True)),
                ('modified_date', models.DateField(blank=True, default=datetime.date.today, help_text=b'Modified Date', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='investigateurlmodel',
            name='url_sha',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='phishverdictmodel',
            name='analysis_stage',
            field=models.IntegerField(choices=[(0, b'New|Waiting'), (1, b'Crawl'), (2, b'Extraction'), (3, b'Query Model'), (4, b'Complete'), (5, b'Offloaded (Single)'), (6, b'Offloaded (Bulk)')], default=0, help_text=b'Verdict Analysis Stage'),
        ),
        migrations.AddField(
            model_name='offloadtasksmodel',
            name='phish_verdict_model',
            field=models.ForeignKey(help_text=b'PhishVerdictModel', on_delete=django.db.models.deletion.CASCADE, related_name='modelqueue_offloadtasksmodel_related', to='modelqueue.PhishVerdictModel', verbose_name=b'PhishVerdictModel FK'),
        ),
    ]
