# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 12:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.IntegerField(choices=[(0, b'Free'), (1, b'Paid Basic')], default=0, help_text=b'License Name')),
                ('description', models.TextField(blank=True, help_text=b'License Description', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLicenseMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.IntegerField(choices=[(0, b'Active'), (1, b'Expired')], default=1, help_text=b'License State')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text=b'IP Address used to register the license', null=True)),
                ('created_date', models.DateField(default=datetime.date.today, help_text=b'Created Date')),
                ('modified_date', models.DateField(default=datetime.date.today, help_text=b'Modified Date')),
                ('license', models.ForeignKey(help_text=b'License', on_delete=django.db.models.deletion.CASCADE, related_name='licenseapp_userlicensemapping_related', to='licenseapp.License', verbose_name=b'License FK')),
                ('requesting_user', models.ForeignKey(help_text=b'User', on_delete=django.db.models.deletion.CASCADE, related_name='licenseapp_userlicensemapping_related', to=settings.AUTH_USER_MODEL, verbose_name=b'User FK')),
            ],
        ),
        migrations.CreateModel(
            name='UserLicenseUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_usage_count', models.IntegerField(default=0, help_text=b'License Usage Count')),
                ('today_usage_count', models.IntegerField(default=0, help_text=b'Today Usage Count')),
                ('userlicensemapper', models.ForeignKey(help_text=b'User License Mapper', on_delete=django.db.models.deletion.CASCADE, related_name='licenseapp_userlicenseusage_related', to='licenseapp.UserLicenseMapping', verbose_name=b'User License Mapper FK')),
            ],
        ),
    ]
